@AI.FinancialKnowledgeCopilot.Api_HostAddress = http://localhost:5016

### Test POST /api/query
POST {{AI.FinancialKnowledgeCopilot.Api_HostAddress}}/api/query
Content-Type: application/json

{
 "query": "What is the latest quarterly revenue?"
}

###

# Response
